### ISSUE TITLE
Update FCM response parsing to v1 API

### ISSUE THREAD

**Issue by jutuon** [rj76/fcm-rust#8]
The code related to FCM response parsing is not yet updated to match v1 API. Docs about v1 API responses are: [Message](https://firebase.google.com/docs/reference/fcm/rest/v1/projects.messages#Message) (other than output fields should be skipped), [FcmError](https://firebase.google.com/docs/reference/fcm/rest/v1/FcmError) and [ApnsError](https://firebase.google.com/docs/reference/fcm/rest/v1/ApnsError).

My [fork](https://github.com/jutuon/fcm-rust/tree/my-main) of this repo currently has partial v1 API response support, so checking out that code might be helpful.

**Comment by rj76** [comment]
Getting that merged somehow would be great!
