### ISSUE TITLE
Support for yup-oauth2

### ISSUE THREAD

**Issue by jutuon** [rj76/fcm-rust#9]
Would it be acceptable to add support for yup-oauth2 here? I would really like to use it as it has token caching to file and it is more popular lib.

If replacing gauth completely is not wanted, then feature flags could be used to replace gauth with yup-oauth2.

My [fork](https://github.com/jutuon/fcm-rust/tree/my-main) already has support for yup-oauth2.

**Comment by rj76** [comment]
In my opinion: definitely. Perhaps as a feature flag first, like you said.

**Comment by rj76** [comment]
Merged. Thank you for this big improvement.
